
name: Code Coverage

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # this service deploys to Cloud Functions using nodejs 10 runtime. We test 12
        # proactively for the future day when we'll upgrade.
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      # if "npm ci" becomes too slow or unreliable, switch to caching dependencies
      # see https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows
      run: npm ci
      working-directory: function
    - name: Make coverage dir
      run: mkdir .nyc_output
      working-directory: function
    - name: Calculate coverage
      run: ./node_modules/.bin/nyc report --reporter=lcov
      working-directory: function
    - name: Upload to codecov
      run: ./node_modules/.bin/codecov
      working-directory: function
