
name: Unit Test and Syntax Lint

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # this service deploys to Cloud Functions using nodejs 10 runtime. We test 12
        # proactively for the future day when we'll upgrade.
        node-version: [10.x, 12.x]

    steps:
    
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      # if "npm ci" becomes too slow or unreliable, switch to caching dependencies
      # see https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows
      run: npm ci
      working-directory: function
    
    - name: Test
      # note that eslint runs on every execution of "npm test" because it is defined as a pretest
      # task in package.json. Thus, we don't need a separate lint action or step.
      run: npm test
      working-directory: function
    
    - name: Calculate coverage
      run: ./node_modules/.bin/nyc report --reporter=lcov > test/coverage.lcov
      working-directory: function
    
    - name: Upload to codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: false
        file: function/test/coverage.lcov
        verbose: false # optional (default = false)



